name: Static Analysis Scan

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  Scan-Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          pwd
          ls
      - name: Perform Scan
        uses: AppThreat/sast-scan-action@master
        with:
          src: "/"
          output: "/reports"
          type: "nodejs"
      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: reports
            

