---
name: Super Linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          # Only fetch JavaScript files
          path: ./
          ref: main
          # Create a sparse checkout to ignore all files except JavaScript files
          sparse-checkout: |
            !**/*.js
            /*.js

      - name: Setup ESLint
        uses: andstor/eslint-action@v4
        with:
          args: .
          extensions: js
...
