name: Super Linter
on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master

jobs:
  super-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JAVASCRIPT: true
          JAVASCRIPT_ES_MULTI: true
          VALIDATE_MARKDOWN: false
          VALIDATE_NATURAL: false
          VALIDATE_SQL: false
          VALIDATE_SQLFLUFF: false
          JAVASCRIPT_STANDARD: 'airbnb'
